### ISSUE TITLE
visceral_fat value different between json and the xiaomi app

### ISSUE THREAD

**Issue by achilles-portarinos** [lolouk44/xiaomi_mi_scale#41]
**Describe the bug**
When getting a measurement, the xiaomi app shows visceral fat 11 whereas the json package says 13.17, not sure if this is normal?

**To Reproduce**
use the xiaomi app to record a measurement, compare the value in the app for visceral fat and the one transmitted in home assistant mqtt service subscription

**Expected behaviour**
the two values do not differ rather than the decimal points
![image](https://user-images.githubusercontent.com/74720145/102007152-e0881b80-3d26-11eb-868f-dd7597328f50.png)
![viber_image_2020-12-13_09-39-19](https://user-images.githubusercontent.com/74720145/102007198-2e048880-3d27-11eb-9055-12f026d6a2e4.jpg)

**Scale (please complete the following information):**
 - Name Mi Body Composition Scale 2
 - Model XMTZC05HM

**Desktop/Server (please complete the following information):**
 - Issue observable both via custom installation (wrapper.sh) as well as via HACS
 - Device Raspberry Pi 4
 - Bluetooth -> internal Bluetooth from rPi 4
 - Version 0.1.14

**Comment by lolouk44** [comment]
Thanks for your report
For info I have not written the formulas to calculate the various values/measures, I've got them from https://github.com/wiecosystem/Bluetooth
The repo has not been updated in over a year and I have no idea when the initial formulas were retrieved / extracted from a mi app.
It is most likely that since these formulas were extracted, Xiaomi has updated them in their app so the results are different.
I have however no android device and even then I have no idea how to extract that info from the mi app...
If this is something you could do I'd welcome your help...

**Comment by achilles-portarinos** [comment]
I see. Oh well, since this is the only value that does not seem to match I thought this could have been something easy to fix. Was wondering actually how nobody has mentioned this issue either here or in the home-assistant forums.

I don't think I can help with this. But maybe you can keep this open for now and let's see if it wins some more attention.

Keep up the good work however, you have already done quite a lot, thanks 👍

**Comment by lolouk44** [comment]
Closing this since it's an old one and I can't really do anything about it
