### ISSUE TITLE
Body Score isnt right - Zepp Life

### ISSUE THREAD

**Issue by AllanOricil** [lolouk44/xiaomi_mi_scale#53]
**Describe the bug**
Impedance values are really close to what I see in the app but the body score computed by your code is 16 points above.

Expected Body Score Value: 49
Actual Body Score Value: 65.21

Zepp Life (former xiaomi app) says my BMI is of someone who is overweight. So this should give me a body score deduction value, but it does not happen:

![image](https://user-images.githubusercontent.com/55927613/163681837-a47ab4c0-188b-4bfd-9908-b3619fd80518.png)

Every Impedance metric is extremely close to what I see in the app, so the body score should also be close enough.

I think these values are wrong

https://github.com/lolouk44/xiaomi_mi_scale/blob/3b5828dad21ee5d21b8315b4f5d6680ca24c2020/src/body_score.py#L48-L49

And I also dont understand why maxMalues is lower than minMalus here. Isn't it inverted?

https://github.com/lolouk44/xiaomi_mi_scale/blob/3b5828dad21ee5d21b8315b4f5d6680ca24c2020/src/body_score.py#L74-L75

My bmi deduction score returns 0 because it reaches this line
https://github.com/lolouk44/xiaomi_mi_scale/blob/3b5828dad21ee5d21b8315b4f5d6680ca24c2020/src/body_score.py#L77

but it should compute something in this one because my bmi is above 25 and below 30 (overweight)
https://github.com/lolouk44/xiaomi_mi_scale/blob/3b5828dad21ee5d21b8315b4f5d6680ca24c2020/src/body_score.py#L75

**Comment by lolouk44** [comment]
Thanks. I'm away at the moment, coming back at the end of the month, I'll look at it then
As a disclaimer, I did not write the body measurement logic, I took it from a [library](https://github.com/wiecosystem/Bluetooth) that was extracted from the Xiaomi app about 3 years ago so it's highly likely the logic has changed and improved since.

**Comment by lolouk44** [comment]
Sorry not getting much time to look into this.
Since you've already identified where the code looks wrong, have you managed to change it for your needs / to make it work?
If so feel free to submit a PR. Please note I've recently rewritten the code to use the bleak library instead of the no longer supported bluepy one.

**Comment by x11x** [comment]
Hi @AllanOricil,
Can I just ask how you are using body_score.py? It does not currently seem to be used anywhere in this repo, you have written your own code importing body_score to generate those tables?
Thanks
