### ISSUE TITLE
Enable support for shelly BT proxy

### ISSUE THREAD

**Issue by Claudio1L** [lolouk44/xiaomi_mi_scale#57]
Hi @lolouk44 

are you planning to support communications with shelly BT proxy?

I did't find a way to make it works.

Thanks
Claudio

**Comment by lolouk44** [comment]
I'm not plannig this because I have limited time at the moment and because I don't have any such device to "play" with.

I'd rather try and make it an HA integration (probably via HACS) as it would simplify things and might actually render it compatible with Shelly BT proxy, though there's a massive learning curve for me to make it work.
I have an alpha version with a single user that I built several weeks ago and haven't touched in a while. No ETA on the integration I'm afraid
